### ISSUE TITLE
Server | Publishing failed

### ISSUE THREAD

**Issue by kanika1901kapoor** [adobe/aem-eclipse-developer-tools#28]
Used the Eclipse AEM plugin(installed from Eclipse marketplace) to create AEM multimodule project (sample-project-archetype-7).
Configured a new server with port, hostname, username  same as that of the running AEM instance and
Server Runtime Environment as Adobe Experience Manager.

But, unable to start server and deploy bundles. Gives following error:
Publishing failed
Could not publish to the server.
Service is null

**Comment by rombert** [comment]
If you go to About Eclipse -> Installation Details do you see something similar to the below screenshot?

You should have an 'AEM Developer Tools' entry with version at least 1.0.2 and two child entries - Sling IDE Tools and Sling IDE Tools, M2e-based with version at least 1.0.4 .

![aem-dev-tools-installation-details](https://cloud.githubusercontent.com/assets/21237/5703489/f5716c28-9a6f-11e4-8112-d2ad1f40f0c0.png)

**Comment by ashlyjose** [comment]
@rombert  this happens when the plugin is installed from Eclipse Marketplace. When installed from marketplace, Sling IDE tools does not get installed. If you check the installation details, you will be able to see only AEM Developer Tools with no child nodes. 

@kanika1901kapoor as a solution/workaround, you can install the plugin directly from http://eclipse.adobe.com/aem/dev-tools/  (please refer the steps in http://docs.adobe.com/docs/en/dev-tools/aem-eclipse.html). This will install the Sling IDE tools as well and there will be no error ! If the installation fails, please restart your eclipse and try again. It will succeed in the second time.

**Comment by rombert** [comment]
@ashlyjose  - thanks for the information and workaround! If that is the case, this is fixed by #23 .

@kanika1901kapoor - can you confirm that the workaround works?

**Comment by saulovenancio** [comment]
Thanks for input. Was not clear to me in the AEM Dev tools if needed to install Sling IDE. Maybe that should be added. 
Thanks.

**Comment by rajeevy69** [comment]
@All, I am getting below error when trying to start my AEM server An internal error occurred during: "Starting Adobe Experience Manager at localhost".
java.lang.ClassNotFoundException: org.apache.jackrabbit.jcr2spi.Jcr2spiRepositoryFactory

Any help is really appreciated.

**Comment by rombert** [comment]
@rajeevy69  - what version of the AEM developer tools for Eclipse and of the Sling IDE tooling do you use?

**Comment by gabrielwalt** [comment]
Closing this as there hasn't been activity since over a year.
