### ISSUE TITLE
JCR Properties not loading in eclipse Neon

### ISSUE THREAD

**Issue by kiranhsgithub** [adobe/aem-eclipse-developer-tools#80]
I am able to successfully install dev tools and can sync files with AEM. But it is currently not showing JCR properties even after I navigate from "Content Navigator".

Logs: 
!ENTRY org.apache.sling.ide.eclipse-core 2 0 2017-08-31 14:05:22.716
!MESSAGE No underlying properties file, cannot derive propertyType (jcr:primaryType) for JcrNode[dom:null, file:L/ui.apps/src/main/content/jcr_root/apps/deg/components/pages/page/crawlingFragment.jsp, jcrPath:/apps/deg/components/pages/page/crawlingFragment.jsp]

![image](https://user-images.githubusercontent.com/7253222/29938358-7f8c841a-8e56-11e7-9b4d-5976e78cdba8.png)

**Comment by rombert** [comment]
Can you upload a minimal project that reproduces the issue? Also, what version of Eclipse and what operating system do you use?

**Comment by jakegarelick** [comment]
I am getting the same error. I am using this tutorial https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part3.html and it happens when I add the cq:htmlTag node. There is a zip file of the project at the top of the pag.e

Eclipse: Version: Neon.3 Release (4.6.3)
Mac: Sierra 10.12.6

I have actually been getting quite a few similar errors throughout this tutorial, so if you did a quick run-through you should be able to break it quite a bit. 

`Exception occurred during analyzing propertyType (class) for DirNode[dom:null, file:F/wknd-sites-guide.ui.apps/src/main/content/jcr_root/apps/wknd/components/structure/header/_cq_htmlTag, jcrPath:/apps/wknd/components/structure/header/cq:htmlTag]`

`No underlying properties file, cannot derive propertyType (jcr:primaryType) for SyncDir[dom:null, file:F/wknd-sites-guide.ui.apps/src/main/content/jcr_root, jcrPath:/]`

**Comment by jakegarelick** [comment]
Actually, after some further research, my `No underlying properties file` error is expected. I'll make a separate issue for another problem I'm having.

**Comment by perfeccionista** [comment]
I am facing same issue on eclipse photon. I see neither JCR properties nor create new -> node on left mouse click options on components node. Selected content module in facets too. Deselected dynamic web module also. Still no luck. Any help much appreciated.

My environment details are
AEM 6.4
Eclipse photon
Windows 10
JDK 1.8

**Comment by dianas06** [comment]
@perfeccionista , Has your issue resolved? I am facing same issue 
AEM 6.4
Eclipse photon
Windows 10
JDK 1.8

**Comment by alezzios** [comment]
I'm running Oxygen with Java 1.8 on macOS Mojave, and JCR properties are not displayed. Also the package explorer doesn't show nodes in JCR style.

**Comment by sridharjayakumar** [comment]
@perfeccionista @dianas06 @alezzios I just got this working , here is my set up
- JDK 1.8 on macOS Catalina with the latest Eclipse IDE 2019-09 build. 
- AEM 6.5, Maven project using archetype 20

Here is how I got it to work
1) I created the project by running the Maven command 
`mvn archetype:generate 
 -DarchetypeGroupId=com.adobe.granite.archetypes
 -DarchetypeArtifactId=aem-project-archetype
 -DarchetypeVersion=20 `

2) After importing the project into eclipse, I didn't see the nodes in the Project Explorer. 
3) Right click on the ui.content and the ui.apps projects in Eclipse and Choose "**Close Project**"
4) Now open up the project folder in terminal and look for a folder called **.settings** under ui.apps and ui.content
5) In this folder, edit the **org.apache.sling.ide.eclipse-core.prefs** file and change the sync root location to read
`org.apache.sling.ide.eclipse-core.content_sync_root=src/main/content/jcr_root`
6) Save the file and make sure it is done for both ui.apps and ui.content
7) Open the ui.apps and ui.content project in Eclipse. Make sure you have chosen "AEM Perspective"

It should now show the nodes and properties as before.

**Comment by alezzios** [comment]
You rock! How did you realize about that?

**Comment by tbodake** [comment]
Thanks a lot @sridharjayakumar !!!
That was really helpful.
